require 'rubygems'
require 'rake/gempackagetask'

GEM_NAME = "lpl-support"
GEM_VERSION = "0.0.1"
AUTHOR = "Fabien Franzen"
EMAIL = "info@atelierfabien.be"
HOMEPAGE = "http://atelierfabien.be/"
SUMMARY = "Enhancements to core Ruby classes and Extlib"

spec = Gem::Specification.new do |s|
  s.rubyforge_project = 'merb'
  s.name = GEM_NAME
  s.version = GEM_VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('extlib', '>= 0.9.9')
  s.add_dependency('mime-types')
  s.require_path = 'lib'
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,spec}/**/*")
  
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "Create a gemspec file"
task :gemspec do
  File.open("#{GEM_NAME}.gemspec", "w") do |file|
    file.puts spec.to_ruby
  end
end